name: Change Auth Key

on:
  schedule:
    - cron: '*/1 * * * *' # Run every minute

jobs:
  change-auth-key:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Change Auth Key
      run: |
        # Generate a new GUID
        new_key=$(python -c "import uuid; print(str(uuid.uuid4()))")

        # Replace the old key in your configuration file
        sed -i "s/AuthKey\": \".*\"/AuthKey\": \"$new_key\"/" path/to/your/config.json

        # Commit and push the changes
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add path/to/your/config.json
        git commit -m "Change Auth Key"
        git push
